hobo/debug/urls.py
# hobo - portal to configure and deploy applications
# Copyright (C) 2015-2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='debug-home'),
]

hobo/seo/urls.py
# hobo - portal to configure and deploy applications
# Copyright (C) 2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='seo-home'),
    path('allow', views.allow, name='robots-allow'),
    path('disallow', views.disallow, name='robots-disallow'),
    path('customize', views.customize, name='robots-customize'),
]

hobo/sms/urls.py
# hobo - portal to configure and deploy applications
# Copyright (C) 2015-2020 Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='sms-home'),
]

hobo/urls.py
# hobo - portal to configure and deploy applications
# Copyright (C) 2015-2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import include, path, re_path

from .applications.urls import urlpatterns as applications_urls
from .debug.urls import urlpatterns as debug_urls
from .emails.urls import urlpatterns as emails_urls
from .environment.urls import urlpatterns as environment_urls
from .maintenance.urls import urlpatterns as maintenance_urls
from .matomo.urls import urlpatterns as matomo_urls
from .profile.urls import urlpatterns as profile_urls
from .security.urls import urlpatterns as security_urls
from .seo.urls import urlpatterns as seo_urls
from .sms.urls import urlpatterns as sms_urls
from .theme.urls import urlpatterns as theme_urls
from .urls_utils import decorated_includes
from .views import admin_required, health_json, hobo, home, login, login_local, logout, menu_json

urlpatterns = [
    path('', home, name='home'),
    re_path(r'^sites/', decorated_includes(admin_required, include(environment_urls))),
    re_path(r'^profile/', decorated_includes(admin_required, include(profile_urls))),
    re_path(r'^visits-tracking/', decorated_includes(admin_required, include(matomo_urls))),
    re_path(r'^theme/', decorated_includes(admin_required, include(theme_urls))),
    re_path(r'^emails/', decorated_includes(admin_required, include(emails_urls))),
    re_path(r'^seo/', decorated_includes(admin_required, include(seo_urls))),
    re_path(r'^sms/', decorated_includes(admin_required, include(sms_urls))),
    re_path(r'^debug/', decorated_includes(admin_required, include(debug_urls))),
    re_path(r'^applications/', decorated_includes(admin_required, include(applications_urls))),
    re_path(r'^maintenance/', decorated_includes(admin_required, include(maintenance_urls))),
    path('', include(security_urls)),
    path('api/health/', health_json, name='health-json'),
    re_path(r'^menu.json$', menu_json, name='menu_json'),
    re_path(r'^hobos.json$', hobo),
]

# add authentication patterns
urlpatterns += [
    path('logout/', logout, name='logout'),
    path('login/', login, name='auth_login'),
    path('login/local/', login_local),  # to be used as backup, in case of idp down
    path('accounts/mellon/', include('mellon.urls')),
]

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar  # pylint: disable=import-error

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hobo/applications/models.py
# hobo - portal to configure and deploy applications
# Copyright (C) 2015-2022 Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import collections
import copy
import io
import json
import os
import sys
import tarfile
import traceback
import urllib.parse

from django.conf import settings
from django.core.files.base import ContentFile
from django.db import connection, models
from django.db.models import JSONField
from django.utils.text import slugify
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.utils.translation import ngettext

from hobo.deploy.signals import notify_agents
from hobo.environment.models import Variable
from hobo.environment.utils import get_installed_services

from .utils import Requests

requests = Requests()


def get_object_types():
    object_types = []
    for service_id, services in getattr(settings, 'KNOWN_SERVICES', {}).items():
        if service_id not in Application.get_supported_modules():
            continue
        service_objects = {x.get_base_url_path(): x for x in get_installed_services(types=[service_id])}
        for service in services.values():
            if service['url'] not in service_objects:
                continue
            if service_objects[service['url']].secondary:
                continue
            url = urllib.parse.urljoin(service['url'], 'api/export-import/')
            response = requests.get(url)
            if not response.ok:
                continue
            for object_type in response.json()['data']:
                object_type['service'] = service
                object_types.append(object_type)
    return object_types


def get_object_type_index(object_type, types):
    try:
        return types.index(object_type)
    except ValueError:
        return 99999


class ApplicationError(Exception):
    def __init__(self, msg, details=None):
        self.msg = msg
        self.details = details


class ScanError(ApplicationError):
    pass


class DeploymentError(ApplicationError):
    pass


class UnlinkError(ApplicationError):
    pass


class Application(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    slug = models.SlugField(max_length=100, unique=True)
    icon = models.FileField(
        verbose_name=_('Icon'),
        help_text=_(
            'Icon file must be in JPEG or PNG format, and should be a square of at least 512×512 pixels.'
        ),
        upload_to='applications/icons/',
        blank=True,
        null=True,
    )
    description = models.TextField(verbose_name=_('Description'), blank=True)
    documentation_url = models.URLField(_('Documentation URL'), blank=True)
    authors = models.TextField(verbose_name=_('Authors'), blank=True)
    license = models.CharField(
        verbose_name=_('License'),
        max_length=200,
        choices=[
            ('', _('Unspecified')),
            # from trove_classifiers License values
            ('agplv3+', _('GNU Affero General Public License v3 or later (AGPLv3+)')),
            ('gplv3+', _('GNU General Public License v3 or later (GPLv3+)')),
            ('mit', _('MIT License')),
        ],
        blank=True,
    )
    editable = models.BooleanField(default=True)
    visible = models.BooleanField(
        verbose_name=_('Visible'),
        help_text=_('If enabled, the application will be visible in the services where it is installed.'),
        default=True,
    )
    elements = models.ManyToManyField('Element', blank=True, through='Relation')
    creation_timestamp = models.DateTimeField(default=now)
    last_update_timestamp = models.DateTimeField(auto_now=True)

    def __repr__(self):
        return '<Application %s>' % self.slug

    @classmethod
    def get_supported_modules(cls):
        return ['wcs', 'combo', 'chrono', 'lingo']

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)[:95]
            slug = base_slug
            i = 1
            while Application.objects.filter(slug=slug).exists():
                slug = '%s-%s' % (base_slug, i)
                i += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def refresh_elements(self, cache_only=False):
        if not cache_only:
            self.relation_set.filter(auto_dependency=True).delete()
            for relation in self.relation_set.all():
                relation.origins.clear()
        remote_elements = {}
        relations = self.relation_set.select_related('element')
        elements = {(x.element.type, x.element.slug): (x.element, x) for x in relations}
        current_object_types = {t for t, s in elements}
        for object_type in get_object_types():
            if object_type['id'] not in current_object_types:
                continue
            if not cache_only and object_type.get('minor'):
                continue
            url = object_type['urls']['list']
            response = requests.get(url)
            if not response.ok:
                raise ScanError(
                    _('Failed to get elements of type %s (%s)' % (object_type['id'], response.status_code)),
                    details=response.text,
                )
            remote_elements[object_type['id']] = {x['id']: x for x in response.json()['data']}
        for element, relation in elements.values():
            if not remote_elements.get(element.type):
                continue
            if not remote_elements[element.type].get(element.slug):
                continue
            remote_element = remote_elements[element.type][element.slug]
            relation.reset_error()
            if cache_only:
                if element.cache == remote_element:
                    continue
                element.cache = remote_element
                element.save()
                elements[(element.type, element.slug)] = (element, relation)
                continue
            if element.name == remote_element['text'] and element.cache == remote_element:
                continue
            element.name = remote_element['text']
            element.cache = remote_element
            element.save()
            elements[(element.type, element.slug)] = (element, relation)
        return elements

    def scandeps(self):
        elements = self.refresh_elements()
        dependencies_url_cache = set()
        finished = False
        while not finished:
            finished = True
            for el, rel in list(elements.values()):
                dependencies_url = el.cache['urls'].get('dependencies')
                if not dependencies_url:
                    continue
                if dependencies_url in dependencies_url_cache:
                    continue
                response = requests.get(dependencies_url)
                if not response.ok:
                    rel.set_error_from_http_code(response.status_code)
                    raise ScanError(
                        _('Failed to scan "%s" (type %s, slug %s) dependencies (%s)')
                        % (el.name, el.type, el.slug, response.status_code),
                        details=response.text,
                    )
                rel.reset_error()
                for dependency in response.json()['data']:
                    if (dependency['type'], dependency['id']) in elements:
                        continue
                    finished = False
                    element, created = Element.objects.get_or_create(
                        type=dependency['type'], slug=dependency['id'], defaults={'name': dependency['text']}
                    )
                    element.name = dependency['text']
                    element.cache = dependency
                    element.save()
                    relation, created = Relation.objects.get_or_create(application=self, element=element)
                    if created:
                        relation.auto_dependency = True
                        relation.save()
                    if self.editable:
                        relation.origins.add(rel)
                    elements[(element.type, element.slug)] = (element, relation)
                dependencies_url_cache.add(dependencies_url)
        return elements

    def unlink(self):
        for service_id, services in getattr(settings, 'KNOWN_SERVICES', {}).items():
            if service_id not in Application.get_supported_modules():
                continue
            service_objects = {x.get_base_url_path(): x for x in get_installed_services(types=[service_id])}
            for service in services.values():
                if service['url'] not in service_objects:
                    continue
                if service_objects[service['url']].secondary:
                    continue
                url = urllib.parse.urljoin(service['url'], 'api/export-import/unlink/')
                response = requests.post(url, data={'application': self.slug})
                if not response.ok:
                    raise UnlinkError(
                        _('Failed to unlink application in module %s (%s)')
                        % (service_id, response.status_code)
                    )

    def get_latest_deployed_version(self):
        last_job = (
            AsyncJob.objects.select_related('version')

hobo/debug/forms.py
# hobo - portal to configure and deploy applications
# Copyright (C) 2015-2019  Entr'ouvert
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_ipv46_address
from django.utils.translation import gettext_lazy as _


def validate_space_separated_ips(value):
    errors = []
    for ip in value:
        try:
            validate_ipv46_address(ip)
        except ValidationError as e:
            errors.append(e)
    if errors:
        raise ValidationError(errors)


class MultipleIPAddressField(forms.CharField):
    default_validators = [validate_space_separated_ips]

    def to_python(self, value):
        if value in self.empty_values:
            return []
        return value.split()

    def prepare_value(self, value):
        if not value:
            return ''
        if not isinstance(value, list):
            return value
        return ' '.join(value)


class SettingsForm(forms.Form):
    debug_log = forms.BooleanField(
        required=False, label=_('Enable Debug Logs'), help_text=_('It will be disabled after 2 hours.')
    )
    debug_ips = MultipleIPAddressField(
        label=_('Internal IP addresses'),
        required=False,
        help_text=_('List of IP addresses for which to enable debugging. It is cleared after 2 hours.'),
    )

hobo/applications/templates/hobo/applications/add-element.html
{% extends "hobo/applications/home.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{{ type.text }}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="application-elements">
      {% for category in categories %}
        <div>
          {% if category.name %}<h4>{{ category.name }}</h4>{% endif %}
          {% for element in category.elements %}
            <label data-slugged-text="{{ element.text|slugify }}"><input
              type="checkbox" name="elements" value="{{ element.id }}">
              {{ element.indentation }}{{ element.text }}</label>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <div style="text-align: right">
      <label>{% trans "Filter:" %} <input type="search" id="element-filter"></label>
    </div>
    <div class="buttons">
      <button class="submit-button">{% trans "Add" %}</button>
      <a class="cancel" href="{% url 'application-manifest' app_slug=app.slug %}">{% trans "Cancel" %}</a>
    </div>
    <script>
      $('#element-filter').on('change blur keyup', function() {
        const val = $(this).val().toLowerCase();
        // force dimensions so a reduced number of elements do not affect size
        $('.application-elements').css('height', $('.application-elements').height());
        $('.application-elements').css('width', $('.application-elements').width());
        if (!val) {
          $('.application-elements div').show();
          $('.application-elements label').show();
        } else {
          $('.application-elements label').each(function(idx, elem) {
            var container = $(elem).parent();
            var slugged_text = $(elem).attr('data-slugged-text');
            if (slugged_text.indexOf(val) > -1) {
              $(elem).show();
              container.show();
            } else {
              $(elem).hide();
              if (!$('label:visible', container).length) {
                container.hide();
              }
            }
          });
        }
      });
    </script>

  </form>
{% endblock %}

hobo/applications/templates/hobo/applications/app_confirm_delete.html
{% extends "hobo/base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% blocktrans with title=object.name %}Removal of "{{ title }}"{% endblocktrans %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>
      {% trans 'Are you sure you want to remove this application?' %}
    </p>
    <p>
      {% trans "Its components won't be removed." %}
    </p>
    <div class="buttons">
      <button class="delete-button">{% trans 'Delete' %}</button>
      <a class="cancel" href="{% url 'application-manifest' app_slug=view.kwargs.slug %}">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock %}

hobo/applications/templates/hobo/applications/check-install.html
{% extends "hobo/applications/manifest.html" %}
{% load i18n thumbnail %}

{% block breadcrumb %}
  {{ block.super }}
  <a href="{% url 'application-confirm-install' app_slug=app.slug version_pk=version.pk %}">{% if last_job.action == 'check-install' %}{% trans "Update" %}{% else %}{% trans "Install" %}{% endif %}</a>
{% endblock %}

{% block appbar %}
  <h2>{{ app.name }} - {% if last_job.action == 'check-install' %}{% trans "Update" %}{% else %}{% trans "Install" %}{% endif %}</h2>
{% endblock %}

{% block content %}
  {% if last_job.status != 'completed' %}
    <div class="pk-error">
      <p>{% trans "Error checking local changes, update can not be run." %}</p>
    </div>
  {% else %}
    {% include "hobo/applications/job_diffs_fragment.html" %}
  {% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="buttons">
      {% if last_job.status == 'completed' %}<button class="submit-button">{% if last_job.action == 'check-install' %}{% trans "Run update" %}{% else %}{% trans "Run install" %}{% endif %}</button>{% endif %}
      <a class="cancel" href="{% url 'application-manifest' app_slug=app.slug %}">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock %}

{% block sidebar %}
{% endblock %}

hobo/applications/templates/hobo/applications/element_config.html
{% extends "hobo/applications/manifest.html" %}
{% load gadjo i18n %}

{% block breadcrumb %}
  {{ block.super }}
  <a href="{% url 'application-element-config' app_slug=app.slug pk=object.pk %}">{{ object.element }}</a>
{% endblock %}

{% block appbar %}<h2>{% blocktrans with object_name=object.element.name object_type_label=object.element.type_label %}Configure {{ object_name }} - {{ object_type_label }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form|with_template }}
    <div class="buttons">
      <button class="submit-button">{% trans "Save" %}</button>
      <a class="cancel" href="{% url 'application-manifest' app_slug=app.slug %}">{% trans "Cancel" %}</a>
    </div>
  </form>
{% endblock %}

{% block sidebar %}
{% endblock %}

hobo/applications/templates/hobo/applications/element_confirm_delete.html
{% extends "hobo/base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% blocktrans with title=object.element.name %}Removal of "{{ title }}"{% endblocktrans %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>
      {% trans 'Are you sure you want to remove this element?' %}
    </p>
    <div class="buttons">
      <button class="delete-button">{% trans 'Delete' %}</button>
      <a class="cancel" href="{% url 'application-manifest' app_slug=view.kwargs.app_slug %}">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock %}

hobo/applications/templates/hobo/applications/manifest.html
{% extends "hobo/applications/home.html" %}
{% load i18n thumbnail %}

{% block breadcrumb %}
  {{ block.super }}
  <a href="{% url 'application-manifest' app_slug=app.slug %}">{{ app.name }}</a>
{% endblock %}

{% block appbar %}
  <h2 class="application-title">
    {% if app.icon %}
      {% thumbnail app.icon '64x64' crop='center' format='PNG' as im %}
        <img src="{{ im.url }}" alt="" />
      {% endthumbnail %}
    {% endif %}
    {{ app.name }}
  </h2>
  <span class="actions">
    <a class="extra-actions-menu-opener"></a>
    {% if app.editable %}
      <a href="{% url 'application-metadata' app_slug=app.slug %}">{% trans 'Metadata' %}</a>
    {% else %}
      <a rel="popup" href="{% url 'application-update' app_slug=app.slug %}">{% trans 'Update' %}</a>
    {% endif %}
    <ul class="extra-actions-menu">
      <li><a href="{% url 'application-versions' app_slug=app.slug %}">{% trans 'See all versions' %}</a></li>
      <li><a rel="popup" href="{% url 'application-delete' slug=app.slug %}">{% trans 'Delete' %}</a></li>
    </ul>
  </span>
{% endblock %}

{% block content %}

  {% if relations %}
    <div class="section padded">
      <label>
        {% trans "Filter label:" %}
        <input type="search" id="name-filter">
      </label>
      <label>
        {% trans "Filter type:" %}
        <select id="type-filter">
          <option value="">----------</option>
          {% for component_type in component_types %}
            {% ifchanged component_type.service.title %}
              {% if forloop.counter0 > 1 %}</optgroup>{% endif %}
              <optgroup label="{{ component_type.service.title }}">
            {% endifchanged %}
            <option value="{{ component_type.id }}">{{ component_type.text }}</option>
          {% endfor %}
        </optgroup>
      </select>
    </label>
    </div>
  {% endif %}
  <script>
    $('#name-filter, #type-filter').on('change blur keyup', function() {
      const name_val = $('#name-filter').val().toLowerCase();
      const type_val = $('#type-filter').val();
      if (!name_val && !type_val) {
        $('.application-content li').show();
      } else {
        $('.application-content li').each(function(idx, elem) {
          var slugged_text = $(elem).attr('data-slugged-text');
          var type = $(elem).attr('data-type');
          if (name_val && type_val) {
            if (slugged_text.indexOf(name_val) > -1 && type == type_val) {
              $(elem).show();
            } else {
              $(elem).hide();
            }
          } else if (name_val) {
            if (slugged_text.indexOf(name_val) > -1) {
              $(elem).show();
            } else {
              $(elem).hide();
            }
          } else if (type_val) {
            if (type == type_val) {
              $(elem).show();
            } else {
              $(elem).hide();
            }
          } else {
            $(elem).hide();
          }
        });
      }
    });
  </script>

  <ul class="objects-list single-links application-content">
    {% for relation in relations %}
      <li data-slugged-text="{{ relation.element.name|slugify }}" data-type="{{ relation.element.type }}" {% if relation.auto_dependency %}class="auto-dependency"{% endif %}>
        <a {% if relation.element.get_redirect_url %}href="{{ relation.element.get_redirect_url }}"{% endif %}>
          {% if relation.error %}<span class="tag tag-error">{{ relation.get_error_status_display }}</span>{% endif %}
          {{ relation.element.name }} <span class="extra-info">- {{ relation.element.type_label }}</span>
        </a>
        {% if app.editable and not relation.auto_dependency %}<a rel="popup" class="delete" href="{% url 'application-delete-element' app_slug=app.slug pk=relation.id %}"><span class="sr-only">{% trans "remove" %}</span></a>{% endif %}
        {% if app.editable and relation.has_origins %}<a rel="popup" data-selector=".popup-origins" class="link-action-icon origins" href="{% url 'application-element-origins' app_slug=app.slug pk=relation.id %}"><span class="sr-only">{% trans "see origins" %}</span></a>{% endif %}
        {% if app.editable and relation.element.has_config_options %}
          <a rel="popup" class="link-action-icon config{% if relation.element.is_config_options_not_default %} marker{% endif %}" href="{% url 'application-element-config' app_slug=app.slug pk=relation.id %}"><span class="sr-only">{% trans "configure" %}</span></a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>

  {% if relations %}
    <div class="buttons">
      {% if app.editable %}
        <a class="pk-button" href="{% url 'application-scandeps' app_slug=app.slug %}">{% trans "Scan dependencies" %}</a>
        &nbsp; &nbsp;
        <a class="pk-button" rel="popup" href="{% url 'application-generate' app_slug=app.slug %}">{% trans "Generate application bundle" %}</a>
      {% endif %}
      {% if last_version and last_version.bundle %}
        {% if app.editable %}&nbsp; &nbsp;{% endif %}
        <a class="pk-button" download href="{% url 'application-download' app_slug=app.slug %}">{% blocktrans with number=last_version.number %}Download latest deployed version ({{ number }}){% endblocktrans %}</a>
      {% endif %}
    </div>
  {% else %}
    <div id="application-empty">
      <div class="infonotice">
        <p>{% trans "You should now assemble the different parts of your application." %}</p>
      </div>
    </div>
  {% endif %}

{% endblock %}

{% block sidebar %}
  <aside id="sidebar">
    {% if not app.editable %}
      <div class="meta">
        {% if app.description %}<p class="description">{{ app.description }}</p>{% endif %}
        {% if app.documentation_url %}<p class="documentation"><a href="{{ app.documentation_url }}">{% trans "Documentation" %}</a></p>{% endif %}
        {% if app.authors %}<p class="authors">{% trans "Created by:" %} {{ app.authors|linebreaksbr }}</p>{% endif %}
        {% if app.license %}<p class="license">{% trans "License:" %} {{ app.get_license_display }}</p>{% endif %}
      </div>
    {% endif %}
    {% if app.editable %}
      <h3>{% trans "Add" %}</h3>
      {% for service, types in types_by_service.items %}
        <h4>{{ service }}</h4>
        {% for type in types %}
          <a class="button button-paragraph" rel="popup" href="{% url 'application-add-element' app_slug=app.slug type=type.id %}">{{ type.text }}</a>
        {% endfor %}
      {% endfor %}
    {% endif %}
    {% with has_parameters=app.parameter_set.exists parameters_qs=app.parameter_set.all %}
      {% if app.editable or has_parameters %}
        <div class="app-parameters--section">
          <h3>{% trans "Parameters" %}
            {% if app.editable %}
              <a rel="popup" href="{% url 'application-add-parameter' app_slug=app.slug %}">({% trans "add" %})</a>
            {% endif %}
          </h3>
          {% if app.editable and has_parameters %}
            <ul class="objects-list single-links app-parameters--list">
              {% for parameter in parameters_qs %}
                <li><a rel="popup" href="{% url 'application-edit-parameter' app_slug=app.slug pk=parameter.id %}">{{ parameter.label }}</a>
                  <a rel="popup" class="delete" href="{% url 'application-delete-parameter' app_slug=app.slug pk=parameter.id %}"><span class="sr-only">{% trans "remove" %}</span></a>
                </li>
              {% endfor %}
            </ul>
          {% elif app.editable %}
            <p>{% trans "No parameters defined." %}</p>
          {% endif %}
          {% if has_parameters %}
            <div class="app-parameters--values">
              {% for parameter in parameters_qs %}
                <p>
                  <label>{{ parameter.label }}</label>
                  {{ parameter.variable.value|default:"-" }}
                  (<a rel="popup" href="{% url 'application-change-parameter-value' app_slug=app.slug name=parameter.variable.name %}">{% trans 'change' %}</a>)
                </p>
              {% endfor %}
            </div>
          {% endif %}
        </div>
      {% endif %}
    {% endwith %}
  </aside>
{% endblock %}